[build]
command = "npm install && npx prisma generate && npm run build"
functions = "netlify/functions"
publish = "dist/"

[[redirects]]
from = "[functions-sub-dir]*"
to = "/.netlify/functions/:splat"
status = 200

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
envPackage = "netlify-plugin-bundle-env"
cypressPackage = "netlify-plugin-cypress"

  [plugins.inputs.preBuild]
    enable = true
    start = 'npm run dev'
    wait-on = 'http://localhost:5173'
    wait-on-timeout = '30' # seconds
    spec = "./cypress/e2e/basic/app-bar.cy.ts"

# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI will inherit
# these settings. You can define environment variables
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository.
[context.production]
publish = "dist/"
command = "npm run build"
environment = { NODE_VERSION = "20.5.0" }

# Here is an example of how to define context-specific
# environment variables. Be mindful when using this
# option and avoid committing sensitive values to public
# source repositories.
[context.deploy-preview.environment]
NOT_PRIVATE_ITEM = "not so secret"

# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch
# will inherit these settings.
[context.branch-deploy]
NODE_ENV = "development"
publish = "dist/"
command = "npm run build"
environment = { NODE_VERSION = "20.5.0" }

# Dev context: environment variables set here
# are available for local development environments
# run using Netlify Dev. These values can be
# overwritten on branches that have a more specific
# branch context configured.
[context.dev.environment]
NODE_ENV = "development"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.staging.environment] # “staging” is a branch name
NODE_ENV = "development"
